---
title: 'Modeling A Primate Technological Niche: Supplementary Tables and Figures'
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      messages = FALSE,
                      dev = "png" )

library(data.table)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(knitr)

source("../ABM_Functions.R")

## Figure theme

base_theme <- theme(axis.text = element_text(size = 5),
                    axis.title = element_text(size = 6),
                    panel.background = element_rect(color = "black", fill = "white"))

## Load Data
run_data <- fread("../Data/EXP_PNAS_run_data.csv")
run_data <- run_data %>% 
  rename(`N Trees` = num_nutree,
         `N Sources` = num_sources)

OGs <- fread("../Data/EXP_PNAS_All_OG.csv")
sources <- fread("../Data/EXP_PNAS_sources.csv")

OGs$d2source <- dist2source(tools = OGs,
                            sources = sources)

OGs <- left_join(OGs, run_data)
```


```{r echo=FALSE, warning=FALSE, message= FALSE, fig.width=6}

run_sum <- run_data[run_data$n_trees_available_start == 0,] %>%
  group_by(`N Sources`, `N Trees`, treessdie) %>%
  summarise(N = n())
nruns_notools <- nrow(run_data[run_data$n_trees_available_start == 0,])/nrow(run_data)

kable(run_sum, caption = "Runs where no tool use events occurred. Note that the majority of runs that did not faciliate tool use are runs with only 100 Trees \\label{no_events}", col.names = c("Number of Sources", "Number of Trees", "Trees Die", "Number of Runs"))

```



```{r SOM Table 3, echo=FALSE, warning=FALSE, message= FALSE}

OGs_sum <- OGs %>% 
  group_by(`N Trees`, `N Sources` , rm_quality) %>% 
  summarise(min_uses = min(n_uses),
            mean_uses = mean(n_uses),
            max_uses = max(n_uses),
            max_d2_source = max(d2source))

kable(OGs_sum[,c(1:7)], 
      caption = "A summary of number of Pounding Tool uses by raw material quality",
      col.names = c("Number of Sources", 
                    "Number of Trees", 
                    "Material Quality",
                    "min N uses",
                    "Mean N Uses",
                    "Max N Uses",
                    "Max Distance to Source"))
```


```{r echo=FALSE, warning=FALSE, message= FALSE}

run_data$new_trees <- run_data$n_trees_available_end - run_data$n_trees_available_start
run_sum <- run_data[run_data$new_trees <= 0] %>%
  group_by(`N Sources`, `N Trees`, treessdie) %>%
  summarise(N = n())

nruns_notools <- nrow(run_data[run_data$n_trees_available_start == 0,])/nrow(run_data)

kable(run_sum, 
      caption = "Runs where the repeated transport of tools did not result in an increase in the number of Tool-use opportunities",
      col.names = c("Number of Sources", "Number of Trees", "Trees Die", "Number of Runs"))
```


```{r SOM Figure 1, fig.cap= "The relationship between the number of places where it is possible for a tool-use event to occur and the number of trees and sources at the beginning of each model run. Increasing both the number of Trees and Sources included in the model has a positive effect on the number of places where tool-use can occur. Note that the Y axis is in log 10 scale"}

ggplot(run_data, aes(x = as.factor(`N Sources`), y = n_trees_available_start, fill = as.factor(`N Trees`)))+
  geom_boxplot()+
  labs(x = "Number of Trees",
       y = "Number of Trees where tool use can occur",
       fill = "Number of sources")+
  scale_y_log10()+
  scale_fill_brewer(palette = "Greys")+
  theme(panel.background = element_rect(color = "black", fill = "white"),
        legend.position = "top")

```


```{r SOM_Figure 2, echo=FALSE, warning=FALSE, message= FALSE, fig.height=6, fig.width=6.5, fig.cap=" Both plots showing the maximum distance _Pounding Tools_ were moved according to their material quality. When the number of Trees is low, material quality has little influence on the maximum distance a _Pounding Tools_ travel, this is due to the fact that there is little opportunity for tools to move substantial distances from their sources. However, as the number of _Trees_ increases, so does the distance _Pounding Tools_ can move from their _Source_. In cases where the number of _Trees_ is great, the maximum distance tools can move is influenced by its raw material quality. Note that a raw material quality of 0 reflects 25% chance of breaking whereas a raw material quality of 75 represents a 100% change of breaking."}

OGs_sum <- OGs %>% 
  group_by(run_id, `N Sources`, `N Trees`, rm_quality) %>% 
  summarise(min_uses = min(n_uses),
            mean_uses = mean(n_uses),
            max_uses = max(n_uses),
            max_d2_source = max(d2source))

OGs_sum <- left_join(OGs_sum, run_data)


ggplot(OGs_sum, aes(x = as.factor(rm_quality), y = max_d2_source)) + 
  geom_boxplot()+
  labs(x = "Material Quality", y= "Max Distance to Source")+
  facet_grid(`N Trees`~`N Sources`, labeller = label_both)+
  theme(panel.background = element_rect(color = "black", fill = "white"), )

```


```{r Tree Growth and Death SOM, echo=FALSE, warning=FALSE, message= FALSE, fig.height=4, fig.width=6.5, fig.cap= "The effect tree death and growth on the maximum distance tools can move from the source. When holding the number of _Trees_ and _Sources_ constant _Pounding Tools_ the maximum distance a pounding tool can move is greater when _Trees_ are able to change their location due to death and regrowth. Black: Static Trees, Grey: Dynamic Trees."}
 
ggplot(OGs_sum, aes(x = as.factor(`N Sources`), y = max_d2_source, fill = as.factor(treessdie))) + 
  geom_boxplot()+
  scale_fill_grey(labels = key)+
  labs(x = " Number of Sources", y = "Max Distance to Source", fill = "Trees Die")+
  facet_grid(~`N Trees`, labeller = label_both)+
  base_theme +
  theme(legend.position = "top")

```


```{r, echo=FALSE, warning=FALSE, message= FALSE, fig.height=4, fig.width=6.5, fig.cap= "The effect tree life cycles on the number of trees that become accessible due to the transport of tools. Black: Static Trees, Grey: Dynamic Trees."}


 ggplot(run_data, aes(x = as.factor(`N Sources`), y = n_trees_available_end, fill = as.factor(treessdie))) +
  geom_boxplot()+
  scale_fill_grey(labels = key)+
  scale_color_grey(labels = key)+
  facet_grid(~`N Trees`, labeller = label_both)+
  labs(x = "Number of Sources", y = "Number of newly available trees", fill = "Trees Die")+
  base_theme + 
  theme(legend.position = "top")
```


```{r echo=FALSE, warning=FALSE, message= FALSE}

tools <- fread("../data/EXP_PNAS_tools.csv")

tools$d2source <- dist2source(tools = tools, sources = sources)

tools_sum <- tools %>% 
  group_by(run_id, x, y) %>%
  summarise(n_tools = n(),
            min_d2_source = min(d2source),
            n_pounding = sum(Tool_size >=2000))


tools_sum <- left_join(tools_sum, run_data)

```


```{r echo=FALSE, warning=FALSE, message= FALSE, fig.height=6, fig.width=6, fig.cap= "The relationship between the number of artifacts found in a grid cell and its distance to the nearest source. Note how the number of _Trees_ attenuates the scale of the distance-decay relationship"}

ggplot(tools_sum[tools_sum$treessdie == 1,], aes(x = min_d2_source, y= n_tools)) + 
  geom_point() +
  labs(x = "Minimum Distance to Source",
       y = "Number of Artifacts") + 
  facet_grid(`N Sources`~`N Trees`, labeller = label_both)+
  base_theme

```


```{r echo=FALSE, warning=FALSE, message= FALSE, fig.height=6, fig.width=6,fig.cap= "The relationship between the number of Pounding Tools found in a grid cell and its distance to the nearest source. Note how the number of _Trees_ attenuates the scale and strength of this relationship"}

OGs_sum <- OGs %>% 
  group_by(run_id,x,y) %>% 
  summarise(max_d2_source = max(d2source),
            min_d2_source = min(d2source),
            n_pounding = n())

OGs_sum <- left_join(OGs_sum, run_data)
ggplot(OGs_sum, aes(x = min_d2_source, y = n_pounding)) + geom_point()+
  facet_grid(`N Sources`~`N Trees`, labeller = label_both)+
    labs(x = "Min Distance to Source",
       y = "N Pounding Tools") + 
  base_theme

```


```{r echo=FALSE, warning=FALSE, message= FALSE, fig.height=6, fig.width=6, fig.cap= "The relationship between the size of Pounding Tools and distance to their sources. Note how the number of _Trees_ attenuates the scale and strength of this relationship"}

ggplot(OGs, aes(x = d2source, y=Tool_size)) + geom_point()+
  facet_grid(`N Sources`~`N Trees`, labeller = label_both)+
      labs(x = "Distance to Source",
       y = "Pounding Tool Size") + 
  base_theme


```


```{r echo=FALSE, warning=FALSE, message= FALSE, fig.height=3, fig.width=3, fig.cap= "The effect of the environment on the representation of Pounding tools in the simulated material record in runs where Tree locations are static. Increasing the number of sources increases the percentage of assemblages that contain Pounding Tools. In comparison with figure 4 (right) in the main text, individual assemblages contain greater proportions of Pounding Tools"}

run_tools_sum <- fread("../data/EXP_PNAS_run_tools_sum.csv")
ggplot(run_tools_sum[run_tools_sum$treessdie == 0,], aes(x = as.factor(num_nutree),
                          y = per_site_pounding, 
                          fill = as.factor(num_sources))) + 
  geom_boxplot()+
  scale_fill_brewer(palette = "Greys")+
  labs(x = "Number of Trees", y = "% of Sites with Pounding Tools", fill = "N Sources")+
  base_theme+
  theme(legend.position = c(.82,.70),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6),
        legend.background = element_blank())+
  theme(aspect.ratio = 1)


```
